### ISSUE TITLE
Run time of OINT

### ISSUE THREAD

**Issue by ZipingZ7** [zrmacc/RNOmni#5]
Dear Dr.McCaw，

Thanks for your great work on these methods.
Recently I am working on a dataset with very positive skewed phenotype. I am using the OINT function to perform association study and finding it very time-consuming. I have around 7k cases and 7.5million SNPs. 
I note that you mentioned RNOmni provides the option of distributing the run time across
cores working in parallel; but i am confused about how to set up NCORES. 

Thank you,
Ziping Z

**Comment by zrmacc** [comment]
Hi Ziping,

Thanks for your interest in the package. While the option to run parallel for loops was included in earlier versions of this package, that option was removed because I found it was more efficient to externally parallelize the workflow. I would suggest one of the following approaches:

1. Divide up your genotypes into B (e.g. 1000) batches, write a script to run OINT on each batch, run all batches in parallel, then concatenate the results. 

2. Prepare a D-INT version of your phenotype (i.e. directly transform Y with `RankNorm`) and an I-INT version of your phenotype (i.e. regress out covariates, then `RankNorm` the residuals). Run GWAS on the D-INT and I-INT versions of your phenotypes using software that has been optimized for GWAS, such as [PLINK](https://www.cog-genomics.org/plink/2.0/). Finally, load the D-INT and I-INT p-values into R and combine the p-values with the `OmniP` function.

Hope that helps!
Zack

**Comment by ZipingZ7** [comment]
Hi Zack,

Thanks for your quick reply! That is really helpful.

I would like to ask further about methods 2: once I get the P-values version both D-INT and  I-INT,do you mean by using omniP function to combine them ? I looked into OmniP function and found that there is only one parameter for P-values (OmniP(p, w = NULL)); also I learned that Pi and Pd are in general positively correlated. 
How can I assign p inside the function?

**Comment by zrmacc** [comment]
Please see the following example on how to combine the p-values:
```
library(dplyr)
library(RNOmni)

# Simulate data for 3 SNPs.
n <- 3
df <- data.frame(
  p_dint = runif(n),
  p_iint = runif(n)
)

# Calculate omnibus p-value.
df <- df %>%
  dplyr::rowwise() %>%
  dplyr::mutate(
    p_omni = RNOmni::OmniP(c(p_dint, p_iint))
  )

```
Yes, correlation between the D-INT and I-INT is expected, and the omnibus calculation allows for it. For additional details, see [Liu and Xie (2019)](https://pmc.ncbi.nlm.nih.gov/articles/PMC7531765/).
